Ethan
PdxCodeGuild/class_swordfish pull request #113
Opened 2022-09-26 19:14 UTC by VanguardAWS

2022-09-26 22:06 UTC, brucestull requested changes
[Lab 9: ATM](https://github.com/PdxCodeGuild/class_swordfish/blob/main/1%20Python/labs/09%20ATM.md)
**Needs Work**
* Comments:
    * Interest is not calculating properly:
        * Interest on `100`:
            * Expected: `.1`
            * But result is `1`

2022-09-26 23:41 UTC, brucestull requested changes
https://github.com/PdxCodeGuild/class_swordfish/pull/113#pullrequestreview-1120895019

2022-09-27 22:37 UTC, VanguardAWS commented on code/ethan/python/lab09.py
> +        self.interest = .01
lab09 fixed

2022-09-27 23:11 UTC, brucestull approved these changes
[Lab 9: ATM](https://github.com/PdxCodeGuild/class_swordfish/blob/main/1%20Python/labs/09%20ATM.md)
**Completed**

2022-09-27 23:11 UTC, merged