Jose
PdxCodeGuild/class_swordfish pull request #117
Opened 2022-09-26 22:58 UTC by jcortes89

completed lab 11, corrected lab 6

2022-10-03 23:25 UTC, jcortes89 commented
Hey Bruce! just sent over the items I needed to fix in 11. Completed lab 9 as well and the HTML lab for today. Let me know if i need to do anything else!

2022-10-04 16:50 UTC, brucestull reviewed
[Lab 9: ATM](https://github.com/PdxCodeGuild/class_swordfish/blob/main/1%20Python/labs/09%20ATM.md)
**Needs Work**
* Comments:
    * Interest on $100:
        * Actual interest accrued:
            * `100.1`
        * Expected interest accrued:
            * `.1`

[Lab 11: Quotes API](https://github.com/PdxCodeGuild/class_swordfish/blob/main/1%20Python/labs/11%20Quotes%20API.md)
**Needs Work**
* Comments:
    * Need to remove pprint statements from console display for user. We want to use the keys to control what the user sees and not show them the whole dictionary response.

2022-10-04 17:03 UTC, brucestull commented on code/jose/Python_Labs/lab11.py
> +        response = requests.get('https://favqs.com/api/quotes/?filter='+keyword+'&type=tag', headers = {'Authorization': 'Token token="855df50978dc9afd6bf86579913c9f8b"'})
* Is there a reason you chose to use `&type=tag`? `filter` will automatically select quotes by `keyword`. Using `&type=tag` will severely reduce number of response quotes.

2022-10-04 17:07 UTC, brucestull requested changes
**Needs Work**

See https://github.com/PdxCodeGuild/class_swordfish/pull/117#pullrequestreview-1130309205

2022-11-03 18:07 UTC, jcortes89 commented
Lab 1 Javascript ready for review

2022-11-03 22:27 UTC, jcortes89 commented
Lab 1 and 2 are complete

2022-11-04 17:07 UTC, brucestull requested changes
[Lab 1-3: Pick 3](https://github.com/PdxCodeGuild/class_swordfish/blob/main/4%20JavaScript/labs/Lab%2001-03%20Pick%203.md)

## Lab 01 - `lab01.js`
**Completed**


## Lab 02 - `lab02.js`
**Needs Work**
* Comments:
    * Many numbers under 10 do not give a response.
    * Input of `75` results in `fiftyseven`, when expected would be something like `seventy five`.

![input](https://user-images.githubusercontent.com/47562501/200034083-91a01d0c-c518-41e0-a31d-6903f5a3f08a.png)
![output](https://user-images.githubusercontent.com/47562501/200034109-54d40723-4477-4be7-a99d-35babdfb1d87.png)


## Lab 03 - `THIRD_CHOICE`
**Not Submitted**

2022-12-01 18:53 UTC, brucestull approved these changes
Merging to start with clean pull request for future labs.

2022-12-01 18:54 UTC, merged