Rachel
PdxCodeGuild/class_swordfish pull request #155
Opened 2022-10-13 21:38 UTC by junedeor

2022-10-13 21:57 UTC, brucestull requested changes
[Lab 1: Bio](https://github.com/PdxCodeGuild/class_swordfish/blob/main/2%20Flask%20%2B%20HTML%20%2B%20CSS/labs/01%20Bio.md)
**Needs Work**
* Comments:
    * Awesome profile, cats are the best!
    * Image file-paths need to be relative file paths to be seen on other computers:
        * Edit file-path for image `Young_Salem.jpeg` so it can be rendered on any computer.

[Lab 2: Company Home](https://github.com/PdxCodeGuild/class_swordfish/blob/main/2%20Flask%20%2B%20HTML%20%2B%20CSS/labs/02%20Company.md)
**Completed**
* Comments:
    * Responsive webpage.
    * Great functionality where images scale with container size rather than hard-coding image sizes.

2022-10-19 17:01 UTC, brucestull commented on code/rachel/HTML/static/lab03_style.css
> +    }
The `@media (min-width: 1000px)` media query needs a closing `}`.

2022-10-21 19:46 UTC, junedeor commented
Lab 03 correction was made and it's ready for review

2022-10-24 16:51 UTC, brucestull approved these changes
[Lab 1: Bio](https://github.com/PdxCodeGuild/class_swordfish/blob/main/2%20Flask%20%2B%20HTML%20%2B%20CSS/labs/01%20Bio.md)
**Completed**

[Lab 3: Blog](https://github.com/PdxCodeGuild/class_swordfish/blob/main/2%20Flask%20%2B%20HTML%20%2B%20CSS/labs/03%20Blog.md)
**Completed**
* Comments:
    * Lab passes.
    * One thing you could or should change:
        * You have links with an href `href="dfsdf"`:
            * This breaks the page, a better way it so use this since it doesn't route to non-existent page:
                * `href="#"`
        * Try it out and see what happens.

2022-10-24 16:51 UTC, merged