Python Mini Capstone + Lab 9 HTML Lab 1 and 2
PdxCodeGuild/class_swordfish pull request #171
Opened 2022-10-24 15:49 UTC by YamilNasser

Python:
Mini Capstone
Lab 9

HTML:
Lab 1
Lab 2

2022-10-26 17:20 UTC, brucestull commented
[Lab 12: Mini Capstone](https://github.com/PdxCodeGuild/class_swordfish/blob/main/1%20Python/labs/12%20Mini-Capstone.md)
**Completed**

2022-10-26 18:08 UTC, brucestull commented on code/yamil/html/lab_4/index.html
> +                Extras:<input type="checkbox" name="extras" value="guacamole" checked>Guac
* The 'name's need to be different for each checkbox.
* [HTML \<input type="checkbox"> - www.w3schools.com](https://www.w3schools.com/tags/att_input_type_checkbox.asp)

2022-10-26 18:20 UTC, brucestull commented on code/yamil/html/lab_4/index.html
> +                Tortilla: <input type="radio" name="tortilla" value="white_flour" checked>White Flour
* Reference:
    * [HTML \<input type="radio"> - www.w3schools.com](https://www.w3schools.com/tags/att_input_type_radio.asp)

2022-10-26 18:22 UTC, brucestull commented on code/yamil/html/lab_5/app.py
> +from flask import Flask, render_template, request
* Application gives incorrect result:
    * See attached image:
![image](https://user-images.githubusercontent.com/47562501/198105840-572c5715-3285-4926-8240-5d447dc6bf7d.png)

2022-10-31 19:21 UTC, YamilNasser commented
Revised and Completed:
Python Lab 9
HTML Lab 4
HTML Lab 5

2022-10-31 20:44 UTC, brucestull requested changes
Python [Lab 9: ATM](https://github.com/PdxCodeGuild/class_swordfish/blob/main/1%20Python/labs/09%20ATM.md)
**Completed**

[Lab 4: Burrito Order Form](https://github.com/PdxCodeGuild/class_swordfish/blob/main/2%20Flask%20%2B%20HTML%20%2B%20CSS/labs/04%20Burrito%20Order%20Form.md)
**Needs Work**
* Comments:
    * Delivery Instructions are currently not being passed to the API.
        * The form element needs an attribute in order to pass the text area's value to the API.
    * Use a `label` element to label the Delivery Instructions element.
        * The text included between the `textarea`s opening and closing tags, in the template, are incorrect. It forces the user to either delete that text or type over it. Use a `placeholder` attribute for text to be displayed for the user. Use a `label` element instead.

[Lab 5: Flask Redo](https://github.com/PdxCodeGuild/class_swordfish/blob/main/2%20Flask%20%2B%20HTML%20%2B%20CSS/labs/05%20Flask%20Redo.md) 
**Completed**

2022-10-31 21:29 UTC, brucestull approved these changes
[Lab 4: Burrito Order Form](https://github.com/PdxCodeGuild/class_swordfish/blob/main/2%20Flask%20%2B%20HTML%20%2B%20CSS/labs/04%20Burrito%20Order%20Form.md)
**Completed**

2022-10-31 21:29 UTC, merged