Ethan - Javascript lab04 in progress
PdxCodeGuild/class_swordfish pull request #196
Opened 2022-11-11 00:33 UTC by VanguardAWS

2022-11-21 22:01 UTC, brucestull requested changes
[Lab 4: Vue Todos](https://github.com/PdxCodeGuild/class_swordfish/blob/main/4%20JavaScript/labs/Lab%2004%20Vue%20Todos.md)
**Completed**

[Lab 5: FavQs in Vue](https://github.com/PdxCodeGuild/class_swordfish/blob/main/4%20JavaScript/labs/Lab%2005%20Quotes%20in%20Vue.md)
**Needs Work**
* Need to clear out search boxes after each search so the previous 'tag' search doesn't show when the user is currently doing an 'author' search. See image below.
* Pagination needs to work. A user needs to be able to see the next and previous pages of quotes if they are available (>25 quotes).
* Need to provide an explicit key for the quote components. See image below.


![image](https://user-images.githubusercontent.com/47562501/203166009-cdb6dc20-cfa8-4ef3-b2f8-82956ce2ad8d.png)
![image](https://user-images.githubusercontent.com/47562501/203166389-79d059ea-cf42-47df-97b5-0c0143e7f413.png)

2022-11-22 20:58 UTC, brucestull reviewed
[Lab 6: Mini-Capstone: Any API in Vue](https://github.com/PdxCodeGuild/class_swordfish/blob/main/4%20JavaScript/labs/Lab%2006%20Mini-Capstone.md)

NOTE: Waiting on student to present application. Will mark lab completed after student presents.

2022-11-29 19:18 UTC, Faebaeee requested changes
[Lab 04 - Django REST Framework](https://github.com/PdxCodeGuild/class_swordfish/blob/main/3%20Django/labs/04%20DRF%20Vue.md)
Try giving this lab a fix, Let me know if you have questions!
![Screen Shot 2022-11-29 at 12 14 01 PM](https://user-images.githubusercontent.com/69445383/204624949-5f7512a5-911a-4e5c-b214-bde451f325f6.png)

2022-11-30 18:23 UTC, brucestull approved these changes
[Lab 5: FavQs in Vue](https://github.com/PdxCodeGuild/class_swordfish/blob/main/4%20JavaScript/labs/Lab%2005%20Quotes%20in%20Vue.md)
**Completed**

2022-11-30 21:28 UTC, brucestull requested changes
[Lab 04 - Django REST Framework](https://github.com/PdxCodeGuild/class_swordfish/blob/main/3%20Django/labs/04%20DRF%20Vue.md)
**Needs Work**
# Comments:
* See inline comments.

2022-11-30 21:28 UTC, brucestull commented on code/ethan/django_lab04/students_app/urls.py
> +    path('/', views.index, name='index'),
![image](https://user-images.githubusercontent.com/47562501/204911464-59cffad5-2969-408f-b04c-3d0fb9cb929c.png)


This `/` needs to be removed and a slash `/` added to the path in `students.urls.py`:
* `path('/', views.index, name='index')` should be `path('', views.index, name='index')`
* `path('api', include('students_app.urls'))` should be `path('api/', include('students_app.urls'))`

## Current config results in the following:
![image](https://user-images.githubusercontent.com/47562501/204911674-4c610ff6-fbe3-41f6-a305-c814008d1f2d.png)
![image](https://user-images.githubusercontent.com/47562501/204911732-1aa88327-29e3-4e3c-ae2a-c278b3f78771.png)

2022-12-02 21:49 UTC, brucestull commented
[Lab 04 - Django REST Framework - Students API](https://github.com/PdxCodeGuild/class_swordfish/blob/main/3%20Django/labs/04%20Students%20API.md)
**Completed**

2022-12-02 22:18 UTC, brucestull commented
[Lab 05 - Pokedex with Django REST Framework and Vue](https://github.com/PdxCodeGuild/class_swordfish/blob/main/3%20Django/labs/05%20Pokedex.md)
* `add` functions properly.

2022-12-02 22:31 UTC, brucestull approved these changes
# Labs completed see links below for specific lab numbers and names.
https://github.com/PdxCodeGuild/class_swordfish/pull/196#issuecomment-1335875971
https://github.com/PdxCodeGuild/class_swordfish/pull/196#issuecomment-1335918995

2022-12-02 22:34 UTC, merged