Julia - lab01_partA and lab02_partA completed
PdxCodeGuild/class_swordfish pull request #221
Opened 2022-11-22 22:32 UTC by juliachobu

Still working on different labs

2022-11-28 21:50 UTC, brucestull commented
[Lab 11: Quotes API](https://github.com/PdxCodeGuild/class_swordfish/blob/main/1%20Python/labs/11%20Quotes%20API.md)
**Needs Work**
* 'new search' gives unexpected results.
* Sample output:
```
Enter 'next page' for more quotes, 'new search' to enter a new search keyword or 'exit' to exit:
 >>> new search
Enter a new keyword:
cat
Marc Jacobs 
 I remember walking the dog one day, I saw a car full of teenage girls, and one of them rolled down the window and yelled, 'Marc Jacobs!' in a French accent. 

Marc Jacobs 
 I remember walking the dog one day, I saw a car full of teenage girls, and one of them rolled down the window and yelled, 'Marc Jacobs!' in a French accent. 

Marc Jacobs 
 I remember walking the dog one day, I saw a car full of teenage girls, and one of them rolled down the window and yelled, 'Marc Jacobs!' in a French accent. 

Marc Jacobs 
 I remember walking the dog one day, I saw a car full of teenage girls, and one of them rolled down the window and yelled, 'Marc Jacobs!' in a French accent.

Marc Jacobs
 I remember walking the dog one day, I saw a car full of teenage girls, and one of them rolled down the window and yelled, 'Marc Jacobs!' in a French accent.

Marc Jacobs
 I remember walking the dog one day, I saw a car full of teenage girls, and one of them rolled down the window and yelled, 'Marc Jacobs!' in a French accent.

Marc Jacobs
 I remember walking the dog one day, I saw a car full of teenage girls, and one of them rolled down the window and yelled, 'Marc Jacobs!' in a French accent.

Marc Jacobs
 I remember walking the dog one day, I saw a car full of teenage girls, and one of them rolled down the window and yelled, 'Marc Jacobs!' in a French accent.

Marc Jacobs
 I remember walking the dog one day, I saw a car full of teenage girls, and one of them rolled down the window and yelled, 'Marc Jacobs!' in a French accent.

Marc Jacobs
 I remember walking the dog one day, I saw a car full of teenage girls, and one of them rolled down the window and yelled, 'Marc Jacobs!' in a French accent.

Marc Jacobs
 I remember walking the dog one day, I saw a car full of teenage girls, and one of them rolled down the window and yelled, 'Marc Jacobs!' in a French accent.

Marc Jacobs
 I remember walking the dog one day, I saw a car full of teenage girls, and one of them rolled down the window and yelled, 'Marc Jacobs!' in a French accent.

Marc Jacobs
 I remember walking the dog one day, I saw a car full of teenage girls, and one of them rolled down the window and yelled, 'Marc Jacobs!' in a French accent.

Marc Jacobs
 I remember walking the dog one day, I saw a car full of teenage girls, and one of them rolled down the window and yelled, 'Marc Jacobs!' in a French accent.

Marc Jacobs
 I remember walking the dog one day, I saw a car full of teenage girls, and one of them rolled down the window and yelled, 'Marc Jacobs!' in a French accent.

Marc Jacobs
 I remember walking the dog one day, I saw a car full of teenage girls, and one of them rolled down the window and yelled, 'Marc Jacobs!' in a French accent.

Marc Jacobs
 I remember walking the dog one day, I saw a car full of teenage girls, and one of them rolled down the window and yelled, 'Marc Jacobs!' in a French accent.

Marc Jacobs
 I remember walking the dog one day, I saw a car full of teenage girls, and one of them rolled down the window and yelled, 'Marc Jacobs!' in a French accent.

Marc Jacobs
 I remember walking the dog one day, I saw a car full of teenage girls, and one of them rolled down the window and yelled, 'Marc Jacobs!' in a French accent.

Marc Jacobs
 I remember walking the dog one day, I saw a car full of teenage girls, and one of them rolled down the window and yelled, 'Marc Jacobs!' in a French accent.

Marc Jacobs
 I remember walking the dog one day, I saw a car full of teenage girls, and one of them rolled down the window and yelled, 'Marc Jacobs!' in a French accent.

Marc Jacobs
 I remember walking the dog one day, I saw a car full of teenage girls, and one of them rolled down the window and yelled, 'Marc Jacobs!' in a French accent.

Marc Jacobs
 I remember walking the dog one day, I saw a car full of teenage girls, and one of them rolled down the window and yelled, 'Marc Jacobs!' in a French accent.

Marc Jacobs
 I remember walking the dog one day, I saw a car full of teenage girls, and one of them rolled down the window and yelled, 'Marc Jacobs!' in a French accent.

Marc Jacobs
 I remember walking the dog one day, I saw a car full of teenage girls, and one of them rolled down the window and yelled, 'Marc Jacobs!' in a French accent.

Enter 'next page' for more quotes, 'new search' to enter a new search keyword or 'exit' to exit:
 >>>
```

2022-11-28 21:54 UTC, brucestull requested changes
[Lab 8: Contact List](https://github.com/PdxCodeGuild/class_swordfish/blob/main/1%20Python/labs/08%20Contact%20List.md)
**Needs Work**
* See inline code comments.

[Lab 9: ATM](https://github.com/PdxCodeGuild/class_swordfish/blob/main/1%20Python/labs/09%20ATM.md)
**Needs Work**
* See inline code comments.

[Lab 10: Dad Joke API](https://github.com/PdxCodeGuild/class_swordfish/blob/main/1%20Python/labs/10%20Dad%20Joke%20API.md)
**Completed**

[Lab 11: Quotes API](https://github.com/PdxCodeGuild/class_swordfish/blob/main/1%20Python/labs/11%20Quotes%20API.md)
**Needs Work**
* See comments section:
    * 'new search' function doesn't work as expected.

[Lab 1: Bio](https://github.com/PdxCodeGuild/class_swordfish/blob/main/2%20Flask%20%2B%20HTML%20%2B%20CSS/labs/01%20Bio.md)
**Completed**

[Lab 1: Grocery List](https://github.com/PdxCodeGuild/class_swordfish/blob/main/3%20Django/labs/01%20Grocery%20List.md)
**Needs Work**
* See inline code comments.

[Lab 1-3: Pick 3](https://github.com/PdxCodeGuild/class_swordfish/blob/main/4%20JavaScript/labs/Lab%2001-03%20Pick%203.md)
**Lab 01 A** - Unit Converter:
* **Needs Work**
* See inline comments in code.

**Lab 02 A** - Blackjack Advice:
* **Needs Work**
* See inline comments in code.

**Lab 03 A** - BlackJack Advice:
* **Needs Work**
* Lab needs to be some python lab other than the two chosen above (Unit Converter, BlackJack Advice).

**Lab 01 B** - Unit Converter:
* **Needs Work**
* In progress.

**Lab 02 B**:
* **Missing**

**Lab 03 B**:
* **Missing**

2022-11-28 21:54 UTC, brucestull commented on code/julia/Javascript/lab01_A/part_A.js
> +// Unit converter
**Needs Work**
* Entered `6` and `ft` and `inches`:
    * Expected about 72 inches.
    * Result is `1.82 inches`.
![image](https://user-images.githubusercontent.com/47562501/204383730-a346a561-3125-4644-83a9-3ea055158ba2.png)

2022-11-28 21:54 UTC, brucestull commented on code/julia/Javascript/lab02_A/part_A.js
> +//Blackjack Advice
**Needs Work**
* Entered:
    * `ace`
    * `10`
    * `2`
    * Expected something like 'bust':
    * Received no output.

2022-11-29 19:56 UTC, brucestull commented
[Lab 8: Contact List](https://github.com/PdxCodeGuild/class_swordfish/blob/main/1%20Python/labs/08%20Contact%20List.md)
**Completed**
* Student demonstrated functionality.

2022-11-29 20:01 UTC, brucestull commented
[Lab 1-3: Pick 3](https://github.com/PdxCodeGuild/class_swordfish/blob/main/4%20JavaScript/labs/Lab%2001-03%20Pick%203.md)
Part A:
* Lab01_Unitconverter:
    * **Completed**
*

2022-11-30 22:05 UTC, Faebaeee approved these changes
Great job!
[Lab 2: Company Home][(https://github.com/PdxCodeGuild/class_swordfish/blob/main/2%20Flask%20%2B%20HTML%20%2B%20CSS/labs/02%20Company.md)
Lab 2 Html/Css Complete

2022-12-01 18:39 UTC, Faebaeee approved these changes
Merging to clean up pull request

2022-12-01 18:40 UTC, merged