Jose
PdxCodeGuild/class_swordfish pull request #77
Opened 2022-09-15 16:34 UTC by jcortes89

Fixed lab 2, completed lab 4 and fixed 5. Working on 6 and will finish soon. Decided to restart it due to me coding my way into a corner and making it far too complicated for me to understand anymore haha :'D Thank you!

2022-09-15 22:42 UTC, brucestull commented
[Lab 5: Credit Card Validation](https://github.com/PdxCodeGuild/class_swordfish/blob/main/1%20Python/labs/05%20Credit%20Card%20Validation.md) has already been completed.

**Completed**

2022-09-15 22:45 UTC, brucestull requested changes
Lab 2 needs work.

2022-09-15 22:45 UTC, brucestull commented on code/jose/Python_Labs/lab02.py
[Lab 2: Number to Phrase](https://github.com/PdxCodeGuild/class_swordfish/blob/main/1%20Python/labs/02%20Number%20To%20Phrase.md)

**Needs Work**

* Input of `104`:
    * Expecter output: `one hundred four`
    * Actual output:
    ```
    PS C:\Users\Bruce\Programming\class_swordfish\code\jose\Python_Labs> python .\lab02.py
    Enter a number: 94
    ninety four
    PS C:\Users\Bruce\Programming\class_swordfish\code\jose\Python_Labs> python .\lab02.py
    Enter a number: 104
    Traceback (most recent call last):
      File "C:\Users\Bruce\Programming\class_swordfish\code\jose\Python_Labs\lab02.py", line 82, in <module>
        print(hundreds_digit + 'hundred',tens_digitwritten[tens_digit],ones[ones_digit])
    KeyError: 0
    PS C:\Users\Bruce\Programming\class_swordfish\code\jose\Python_Labs>
    ```

2022-09-15 22:45 UTC, brucestull commented on code/jose/Python_Labs/lab04.py
>      return numbers
[Lab 4: Pick6](https://github.com/PdxCodeGuild/class_swordfish/blob/main/1%20Python/labs/04%20Pick%206.md)

**Completed**

2022-09-16 23:33 UTC, closed without merging

2022-09-16 23:33 UTC, jcortes89 commented
just closing to reopen a new one to pull my lab 7 into the branch since it is completed