Alden
PdxCodeGuild/class_swordfish pull request #92
Opened 2022-09-19 23:50 UTC by Alden-Addor

Finished right at the end of class today!!

2022-09-20 17:47 UTC, brucestull commented on code/alden/python/lab08.py
> +import re
Needs Work:
* REPL should keep looping until the user decides to end the loops.
    * User should be able to do the four CRUD without having to restart the python program.
* See me if you have any questions.

2022-09-20 17:49 UTC, brucestull requested changes
[Lab 8: Contact List](https://github.com/PdxCodeGuild/class_swordfish/blob/main/1%20Python/labs/08%20Contact%20List.md)

Needs Work:
* User should be able to repeatedly do any of the four CRUD operations and then have some option to 'exit' or 'quit' when they are finished.

2022-09-20 20:52 UTC, Alden-Addor commented
Updated to use a REPL to keep 'user' going until they wish to leave.  Sorry, I definitely missed that in the instructions.

2022-09-21 16:55 UTC, brucestull commented
Much appreciation for updating Pull Request Title. It makes tracking lab reviews more effective and effictient.

2022-09-21 17:03 UTC, brucestull approved these changes
[Lab 8: Contact List](https://github.com/PdxCodeGuild/class_swordfish/blob/main/1%20Python/labs/08%20Contact%20List.md)

**Completed**

Great Job!
* Good use of flavor text.

2022-09-21 17:03 UTC, brucestull commented on code/alden/python/lab08.py
> +with open('contacts.csv', 'w') as phone_book_file:  # Writes over the .csv file, updating any changes.
Logic above works as necesary so the final write overwrites the file and we can access that same file again.

Great job!

2022-09-21 17:03 UTC, merged